mutation SaveMediaListEntry($mediaId: Int, $status: MediaListStatus, $progress: Int, $progressVolumes: Int, $score: Float, $advancedScores: [Float], $repeat: Int, $priority: Int, $notes: String, $startedAt: FuzzyDateInput, $completedAt: FuzzyDateInput, $customLists: [String], $private: Boolean, $hiddenFromStatusLists: Boolean) {
  SaveMediaListEntry(mediaId: $mediaId, status: $status, progress: $progress, progressVolumes: $progressVolumes, score: $score, advancedScores: $advancedScores, repeat: $repeat, priority: $priority, notes: $notes, startedAt: $startedAt, completedAt: $completedAt, customLists: $customLists, private: $private, hiddenFromStatusLists: $hiddenFromStatusLists) {
    id
    status
    progress
    progressVolumes
    score
    advancedScores
    repeat
    priority
    notes
    startedAt { year month day }
    completedAt { year month day }
    customLists
    private
    hiddenFromStatusLists
  }
}
