query GetUserLibrary($username: String!, $type: MediaType!) {
  MediaListCollection(userName: $username, type: $type) {
    user {
      id
      mediaListOptions {
        scoreFormat
        animeList { customLists advancedScoring advancedScoringEnabled }
        mangaList { customLists advancedScoring advancedScoringEnabled }
      }
    }
    lists {
      name
      isCustomList
      entries {
        id
        media {
          id
          title {
            userPreferred
            romaji
            english
            native
          }
          coverImage {
            medium
            large
            extraLarge
          }
          episodes
          chapters
          volumes
          type
          format
          status
          genres
          nextAiringEpisode {
            episode
            timeUntilAiring
            airingAt
          }
          startDate {
            year
            month
            day
          }
        }
        status
        progress
        progressVolumes
        score
        advancedScores
        repeat
        notes
        startedAt {
          year
          month
          day
        }
        completedAt {
          year
          month
          day
        }
        priority
        private
        hiddenFromStatusLists
        updatedAt
        createdAt
      }
    }
  }
}
